#! /bin/sh

set -e
set -x

# Backup my most important files in a USB disk I shall always carry.

FILES="\
$HOME/Documents/keepass.kdbx \
$HOME/.gnupg/pubring.gpg \
$HOME/.gnupg/secring.gpg \
$HOME/.gnupg/trustdb.gpg \
$HOME/Documents/gpg/my_keys/*.asc \
$HOME/.ssh/*"

sudo cryptsetup luksOpen /dev/disk/by-uuid/57d7dadc-cb54-4b2b-9190-429de0578580 my-disk
sudo mount /dev/mapper/my-disk /mnt

rsync -av ${FILES} /mnt/backup/

sudo umount /mnt
sudo cryptsetup luksClose my-disk
sync
