#! /bin/sh

# This requieres a user 'browsing' with access to the video group:
# `sudo useradd -m -G audio,video -s /bin/bash browsing`
#
# Then add the following line in `visudo` (assuming my user is in the 'wheel'
# group')
# %wheel ALL=(browsing) NOPASSWD: ALL
#
# We add our user to the grou 'browsing'
# sudo usermod -aG browsing black
#
# Change umask so the regular user can read and write the 'browsing' user files
# sudo -iH -u browsing sh -c 'echo "umask 007" >> ~/.profile'
#
# Link Downloads folder to my home
# ln -s /home/browsing/Downloads ~/
#
# Get PulseAudio working
# cp /etc/pulse/default.pa ~/.config/pulse/default.pa
# Edit the file to have this line
# load-module module-native-protocol-unix socket=/tmp/pulse-server
# Add to /etc/pulse/daemon.conf
# enable-memfd = yes
# On every client, in ~/.config/pulse/client.conf
# default-server = /tmp/pulse-server
# enable-memfd = yes
# Copy the cookies probably
# Launch firejail with --whitelist=/tmp/pulse-server --whitelist=~/.pulse-cookie

usr=browsing

xhost local:$usr
cp -R ~/.config/pulse/cookie /home/$usr/pulse_cookie
chmod 770 /home/$usr/pulse_cookie
chown black:$usr /home/$usr/pulse_cookie

sudo -iH -u $usr cp /home/$usr/pulse_cookie /home/$usr/.config/pulse/cookie
sudo -iH -u $usr cp /home/$usr/pulse_cookie /home/$usr/.pulse-cookie
sudo -iH -u browsing firejail --seccomp firefox $@
