#! /bin/sh

set -e

exec chromium \
  --proxy-server="socks://localhost:9050" \
  --load-and-launch-app=/home/black/.config/chromium/Default/Extensions/bikioccmkafdpakkkcpdbppfkghcmihk/0.32.0_0/

#exec chromium \
#  --proxy-server="socks://localhost:9050" \
