#! /bin/sh

sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
#sudo openvpn ~/VPN/AirVPN_Czech-Republic_UDP-2018.ovpn
#sudo openvpn ~/VPN/AirVPN_France_UDP-2018.ovpn
sudo openvpn ~/VPN/AirVPN_Germany_UDP-2018.ovpn
