#! /bin/sh

# sudo modprobe btusb
# sudo modprobe uinput
# sudo systemctl start bluetooth.service
sudo hciconfig hci0 up

if [ "$1" = "gamepad" ]
then
    wminput -c /home/black/.CWiid/gamepad.conf
else
    wminput -c /home/black/.CWiid/wminput.conf
fi
