#! /bin/sh

# sudo modprobe btusb
# sudo systemctl start bluetooth.service
sudo modprobe uinput
#sudo hciconfig hci0 up
sudo btmgmt power on

if [ "$1" = "gamepad" ]
then
    wminput -c /home/black/.CWiid/gamepad.conf
else
    wminput -c /home/black/.CWiid/wminput.conf
fi
